### ISSUE TITLE
[Bug] usermod: user '$USER' does not exist

### ISSUE THREAD

**Issue by Obijuan** [FPGAwars/apio#171]
* Apio version: 0.4.0
* Operating System: Ubuntu 18.04

The first time the command apio drivers --serial-enable is execute, there is an error message:
```
usermod: user '$USER' does not exist
```
and the user is not added to the serial port group. For this reason, is not possible to upload into boards such an TinyFPGABx

For making the board works, this command should be type directly:

sudo usermod -a -G dialout $USER

(and restart the session)

This is the commands for reproducing the error:

```
obijuan@Dagobah:~$ apio drivers --serial-disable
Revert Serial drivers' configuration
Serial drivers disabled
Unplug and reconnect your board
obijuan@Dagobah:~$ apio drivers --serial-enable
Configure Serial drivers for FPGA
usermod: user '$USER' does not exist
Serial drivers enabled
Unplug and reconnect your board
obijuan@Dagobah:~$
```

**Comment by Jesus89** [comment]
Good catch Juan!

I have fixed the issue in the master branch. You can install and test the branch `pip install git+https://github.com/fpgawars/apio`.

The `--serial-enable` command should add the `dialout` group if it is not added and show the message `Restart your session to enable the dialout group`.

The `--serial-disable` does not remove the group, so you should do it manually for the tests.

I'm almost sure that the `dialout` group is not needed for FTDI boards but it would be nice if you can check that too.

Thanks.

**Comment by kelu124** [comment]
Hi ! Similar issue there, using apio 0.4.0

The message still appears, and even while adding `sudo usermod -a -G dialout $USER` I get the following error which does not allow me to upload. Note that the flash ID is still read..

`iceprog -d i:0x0403:0x6014:0 hardware.bin
init..
cdone: high
reset..
cdone: high
flash ID: 0xEF 0x40 0x16 0x00
file size: 104090
erase 64kB sector at 0x000000..
Read error.
ABORT.
scons: *** [upload] Error 2
======================================================== [ ERROR ] Took 1.19 seconds ========================================================
pi@pifore:~/fpga/fpga101-workshop/tutorials/01-Basics $ apio upload
[Sat Jul  6 17:49:01 2019] Processing fpga101
----------------------------------------------------------------------------------------------------------------------------------------------
iceprog -d i:0x0403:0x6014:0 hardware.bin
init..
Read error.
ABORT.
scons: *** [upload] Error 2
`

Apologies in advance if the solution is somehow indicated somewhere, and many thanks in advance.
